using System.Collections.Generic;

namespace RecyclerViewer
{
    // Album: contains image resource ID and caption:
    public class Album
    {
        // Caption text for this photo:
        public string mCaption;
        // Album ID for this photo:
        public int mItemId;

        public List<int> mPhotos;

        public Album()
        {
            mPhotos = new List<int>();
        }

        // Return the ID of the photo:
        public int ItemId
        {
            get { return mItemId; }
        }

        // Return the Caption of the photo:
        public string Caption
        {
            get { return mCaption; }
        }
    }

    // Album album: holds image resource IDs and caption:
    public class Library
    {
        // Built-in photo collection - this could be replaced with
        // a photo database:

        private static readonly Album[] _mBuiltInAlbums =
        {
            new Album
            {
                mItemId = 0,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates
                }
            },
            new Album
            {
                mItemId = 1,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates
                }
            },
            new Album
            {
                mItemId = 2,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.royal_mile,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.edinburgh_castle_2,
                    Resource.Drawable.edinburgh_castle_1
                }
            },
            new Album
            {
                mItemId = 3,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.edinburgh_from_on_high,
                    Resource.Drawable.old_meets_new,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.tower_of_london,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.royal_mile,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park
                }
            },
            new Album
            {
                mItemId = 4,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.royal_mile,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.tower_of_london
                }
            },
            new Album
            {
                mItemId = 5,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.museum_and_castle,
                    Resource.Drawable.portcullis_gate,
                    Resource.Drawable.to_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.tower_of_london
                }
            },
            new Album
            {
                mItemId = 6,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.pompidou_centre,
                    Resource.Drawable.heres_lookin_at_ya,
                    Resource.Drawable.museum_and_castle,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.portcullis_gate,
                    Resource.Drawable.to_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert
                }
            },
            new Album
            {
                mItemId = 0,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates
                }
            },
            new Album
            {
                mItemId = 1,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates
                }
            },
            new Album
            {
                mItemId = 2,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.royal_mile,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.edinburgh_castle_2,
                    Resource.Drawable.edinburgh_castle_1
                }
            },
            new Album
            {
                mItemId = 3,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.edinburgh_from_on_high,
                    Resource.Drawable.old_meets_new,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.tower_of_london,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.royal_mile,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park
                }
            },
            new Album
            {
                mItemId = 4,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.royal_mile,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.tower_of_london
                }
            },
            new Album
            {
                mItemId = 5,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.museum_and_castle,
                    Resource.Drawable.portcullis_gate,
                    Resource.Drawable.to_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.tower_of_london
                }
            },
            new Album
            {
                mItemId = 6,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.pompidou_centre,
                    Resource.Drawable.heres_lookin_at_ya,
                    Resource.Drawable.museum_and_castle,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.portcullis_gate,
                    Resource.Drawable.to_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert
                }
            },
            new Album
            {
                mItemId = 0,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates
                }
            },
            new Album
            {
                mItemId = 1,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates
                }
            },
            new Album
            {
                mItemId = 2,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.royal_mile,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.edinburgh_castle_2,
                    Resource.Drawable.edinburgh_castle_1
                }
            },
            new Album
            {
                mItemId = 3,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.edinburgh_from_on_high,
                    Resource.Drawable.old_meets_new,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.tower_of_london,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.royal_mile,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park
                }
            },
            new Album
            {
                mItemId = 4,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.royal_mile,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.tower_of_london
                }
            },
            new Album
            {
                mItemId = 5,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.museum_and_castle,
                    Resource.Drawable.portcullis_gate,
                    Resource.Drawable.to_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.tower_of_london
                }
            },
            new Album
            {
                mItemId = 6,
                mCaption = "Buckingham Palace",
                mPhotos =
                {
                    Resource.Drawable.pompidou_centre,
                    Resource.Drawable.heres_lookin_at_ya,
                    Resource.Drawable.museum_and_castle,
                    Resource.Drawable.la_tour_eiffel,
                    Resource.Drawable.louvre_1,
                    Resource.Drawable.before_mobile_phones,
                    Resource.Drawable.big_ben_1,
                    Resource.Drawable.london_eye,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.arc_de_triomphe,
                    Resource.Drawable.eurostar,
                    Resource.Drawable.louvre_2,
                    Resource.Drawable.versailles_fountains,
                    Resource.Drawable.modest_accomodations,
                    Resource.Drawable.notre_dame,
                    Resource.Drawable.inside_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.seine_river,
                    Resource.Drawable.rue_cler,
                    Resource.Drawable.champ_elysees,
                    Resource.Drawable.seine_barge,
                    Resource.Drawable.versailles_gates,
                    Resource.Drawable.portcullis_gate,
                    Resource.Drawable.to_notre_dame,
                    Resource.Drawable.tower_visitors,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert,
                    Resource.Drawable.scott_monument,
                    Resource.Drawable.edinburgh_station,
                    Resource.Drawable.view_from_holyrood_park,
                    Resource.Drawable.one_o_clock_gun,
                    Resource.Drawable.victoria_albert
                }
            }
        };

        // Array of photos that make up the album:
        private readonly Album[] mItems;

        // Create an instance copy of the built-in photo list and
        // create the random number generator:
        public Library()
        {
            mItems = _mBuiltInAlbums;
        }

        // Return the number of photos in the photo album:
        public int NumAlbums
        {
            get { return mItems.Length; }
        }

        // Indexer (read only) for accessing a photo:
        public Album this[int i]
        {
            get { return mItems[i]; }
        }

        public List<int> GetItems(int i)
        {
            return mItems[i].mPhotos;
        }
    }
}